name: code-quality

on:
  push:
    branches:
      - master
    tags:
    paths:
      - '**.py'
      - .github/workflows/code_quality.yml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/code_quality.yml
  workflow_dispatch:

jobs:
  linting:
    name: Code-quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [isort, black]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
